#!/bin/bash

echo "export GTK_THEME=Adwaita:dark" > ~/.xinitrc
echo "setxkbmap -option caps:escape_shifted_capslock" >> ~/.xinitrc
echo "xrandr --output HDMI1 --above eDP1" >> ~/.xinitrc
echo "exec i3" >> ~/.xinitrc

echo '[[ -z "$TMUX" ]] && tmux' >> ~/.bashrc
echo "alias is='sudo pacman -S'" >> ~/.bashrc
echo "alias ss='sudo pacman -Ss'" >> ~/.bashrc
echo "alias qs='sudo pacman -Qs'" >> ~/.bashrc
echo "alias up='sudo pacman -Syyu'" >> ~/.bashrc
echo "alias gy='git clone https://aur.archlinux.org/yay ; cd yay ; makepkg -si'" >> ~/.bashrc

echo "unbind C-b" >> ~/.tmux.conf
echo "set-option -g prefix C-a" >> ~/.tmux.conf
echo "bind C-a send-prefix" >> ~/.tmux.conf
echo "set -g mouse on" >> ~/.tmux.conf
echo "set -g @scroll-speed-num-lines-per-scroll 20" >> ~/.tmux.conf

echo 'if [ -z "$DISPLAY" ] && [ "$XDG_VTNR" = 1 ]; then' >> ~/.bashrc
echo "exec startx" >> ~/.bashrc
echo "fi" >> ~/.bashrc

sudo pacman -S --needed base-devel intel-ucode xorg xorg-xinit xf86-video-intel i3 alacritty vim dmenu chromium brightnessctl ranger htop tmux pipewire pipewire-alsa pipewire-pulse pipewire-jack git
