#!/bin/bash

echo "export GTK_THEME=Adwaita:dark" > ~/.xinitrc
echo "setxkbmap -option caps:escape_shifted_capslock" >> ~/.xinitrc
echo "xrandr --output HDMI1 --above eDP1" >> ~/.xinitrc
echo "exec i3" >> ~/.xinitrc

echo '[[ -z "$TMUX" ]] && tmux' >> ~/.bashrc
echo "alias is='sudo pacman -S'" >> ~/.bashrc
echo "alias ss='sudo pacman -Ss'" >> ~/.bashrc
echo "alias qs='sudo pacman -Qs'" >> ~/.bashrc
echo "alias up='sudo pacman -Syyu'" >> ~/.bashrc
echo "alias gy='git clone https://aur.archlinux.org/yay ; cd yay ; makepkg -si'" >> ~/.bashrc

echo "unbind C-b" >> ~/.tmux.conf
echo "set-option -g prefix C-a" >> ~/.tmux.conf
echo "bind C-a send-prefix" >> ~/.tmux.conf
echo "set -g mouse on" >> ~/.tmux.conf
echo "set -g @scroll-speed-num-lines-per-scroll 20" >> ~/.tmux.conf

sudo pacman -S --needed base linux linux-firmware intel-ucode sudo xorg xorg-xinit i3 alacritty networkmanager grub efibootmgr base-devel chromium xf86-video-intel libva-intel-driver vulkan-intel htop dmenu tmux pipewire pipewire-alsa pipewire-pulse pipewire-jack brightnessctl vim fzf git vlc ranger
