#!/bin/bash

parted /dev/nvme0n1 mklabel gpt
parted /dev/nvme0n1 mkpart primary ext4 0GB 1GB
parted /dev/nvme0n1 mkpart primary ext4 1GB 100%

mkfs.vfat /dev/nvme0n1p1
mkfs.ext4 /dev/nvme0n1p2

mount /dev/nvme0n1p2 /mnt
mount --mkdir /dev/nvme0n1p1 /mnt/boot

pacstrap -K /mnt base linux linux-firmware intel-ucode sudo networkmanager grub efibootmgr

arch-chroot /mnt
useradd -mG wheel -s /bin/bash d
grub-install --efi-directory=/boot
grub-mkconfig -o /boot/grub/grub.cfg
systemctl enable NetworkManager

sed -i '125s/^#/ /' /etc/sudoers
echo "setxkbmap -option caps:escape_shifted_capslock" > /home/d/.xinitrc
echo "xrandr --output HDMI1 --above eDP1" >> /home/d/.xinitrc
echo "exec i3" >> /home/d/.xinitrc
echo "alias i='sudo pacman -S'" >> /home/d/.bashrc
echo "alias c='startx'" >> /home/d/.bashrc
echo "sudo pacman -S --needed base-devel vim xorg xorg-xinit xf86-video-intel xdg-utils i3 alacritty rofi chromium vlc ffmpeg inxi fzf git firefox curl sed brightnessctl ranger htop tmux rofi pipewire pipewire-alsa pipewire-pulse pipewire-jack zip unzip thunar file-roller pavucontrol chromium" >> lol

